language: java
jdk:
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_ea5617bfdeba_key -iv $encrypted_ea5617bfdeba_iv
  -in private_key_sender.asc.enc -out private_key_sender.asc -d
- chmod +x gradlew
after_success:
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -Ls https://coverage.codacy.com/get.sh)
deploy:
  provider: script
  script: "./gradlew deploy"
  skip_cleanup: true
  dry-run: false
