language: java
jdk:
- openjdk8

before_install:
  - openssl aes-256-cbc -K $encrypted_39a29b9bceb4_key -iv $encrypted_39a29b9bceb4_iv -in pubring.gpg.enc -out pubring.gpg -d
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)

deploy:
  provider: script
  script: "./gradlew deploy -Psigning.keyId=${KEY_ID} -Psigning.password=${KEY_PASS} -Psigning.secretKeyRingFile=pubring.gpg"
  skip_cleanup: true
  dry-run: false
  branches:
    only:
      - master
      - /.*@[0-9]+\.[0-9]+\.[0-9]+/